### ISSUE TITLE
minits -> minutes

### ISSUE THREAD

**Issue by mjk0513** [haruto0/kintai#5]
配列で時刻管理してるけど、　UIDatePicker使うと良さみかもしれない

**Comment by mjk0513** [comment]
UIDatePickerで勤務開始時間と終了時間を選択、そこから計算して勤務時間を算出。
のほうがよさみだね
あとはそのログをUserDefaultsかCoreDataで管理、または自分でPHPとかでバックエンド組んでクラウド化するかｗ

**Comment by haruto0** [comment]
なるほど
やってみます！

**Comment by mjk0513** [comment]
https://developer.apple.com/documentation/uikit/uidatepicker

**Comment by haruto0** [comment]
これがやりたかったんですよ！

**Comment by mjk0513** [comment]
👍👍👍
